# Generated by Django 3.1.3 on 2020-11-05 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movierec', '0002_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='userId',
        ),
    ]
