# Generated by Django 3.1.3 on 2020-11-07 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movierec', '0004_rating_userid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
