# Generated by Django 3.1.3 on 2020-11-07 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movierec', '0008_auto_20201107_1318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='rater',
            new_name='userId',
        ),
    ]
