# Generated by Django 3.1.3 on 2020-11-07 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movierec', '0010_auto_20201107_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
